DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY, 
    task_title VARCHAR(256) NOT NULL, 
    is_done BOOLEAN NOT NULL DEFAULT false,
    date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_done TIMESTAMP NULL
);
